version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # "/" for the default location of `.github/workflows`
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "monthly"