name: deepfcd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - antspyx==0.3.8 --only-binary=antspyx
    - antspynet==0.2.0
    - git+https://github.com/ravnoor/atlasreader@master#egg=atlasreader
    - Theano==1.0.4
    - keras==2.2.4
    - h5py==2.10.0
    - matplotlib==3.5.1
    - mo-dots==9.147.22086
    - nibabel==3.2.2
    - nilearn==0.9.1
    - numpy==1.18.5
    - pandas==1.3.5
    - psutil==5.9.2
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - setproctitle==1.2.3
    - tabulate==0.9.0
    - tqdm==4.64.0
    - xlrd==2.0.1
    - tensorflow==1.15.5
    - tensorflow_probability==0.8
    - --extra-index-url https://download.pytorch.org/whl/lts/1.8/cpu
    - gast<=0.4.0,>=0.2.1
    - torchsummary==1.5.1
    - torch==1.8.2
    - torchvision==0.9.2
    - pybids
    - protobuf==3.20.3
    - pygpu==0.7.6
