blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/NOEL-MNI/deepFCD/blob/main/README.md
    about: Check the documentation for setup and usage instructions
  - name: Discussions
    url: https://github.com/NOEL-MNI/deepFCD/discussions
    about: Ask questions and discuss ideas with the community
