name: deepfcd
channels:
  - conda-forge
dependencies:
  - python==3.8
  - pygpu==0.7.6
  - pip
  - pip:
    - antspyx==0.4.2
    - atlasreader==0.1.2
    - Theano==1.0.4
    - keras==2.2.4
    - h5py==2.10.0
    - matplotlib==3.5.1
    - mo-dots==9.147.22086
    - nibabel==3.2.2
    - nilearn==0.9.1
    - numpy==1.21.6
    - pandas==1.3.5
    - psutil==5.9.2
    - scikit-image==0.19.2
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - setproctitle==1.2.3
    - tabulate==0.9.0
    - tqdm==4.65.0
    - xlrd==2.0.1