services:
  runner:
    image: noelmni/deep-fcd_ci:cu118-cudnn8-ubuntu22.04
    # command: '/app/inference.py FCD_001 T1.nii.gz FLAIR.nii.gz /io cuda0 1 1'
    # command: nvidia-smi
    # entrypoint: /bin/bash
    build:
      context: .
      dockerfile: runner.Dockerfile
      args:
        RUNNER_VERSION: 2.325.0
        MAMBA_VERSION: 2.2.0-0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              # device_ids: ['1']
              capabilities: [gpu,compute,video]
    # volumes:
        # - '$PWD/io:/io'
        # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
