services:
  runner:
    image: noelmni/deep-fcd_ci:cu122-ubuntu22.04-miniforge
    # command: '/app/inference.py FCD_001 T1.nii.gz FLAIR.nii.gz /io cuda0 1 1'
    # command: nvidia-smi
    # entrypoint: /bin/bash
    build:
      context: .
      dockerfile: runner.Dockerfile
      args:
        BASE_IMAGE_TAG: 12.2.2-cudnn8-devel-ubuntu22.04
        RUNNER_VERSION: '2.328.0'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              device_ids: ['0']
              capabilities: [gpu,compute,video]
    # volumes:
        # - '$PWD/io:/io'
        # - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
