name: Test Docker image build

on: [push, pull_request]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false