name: Test Docker image build

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      build_main:
        description: 'Build main deepFCD image'
        required: false
        default: 'true'
        type: boolean
      build_ci:
        description: 'Build CI runner image'
        required: false
        default: 'true'
        type: boolean

env:
  MAIN_IMAGE_NAME: noelmni/deepfcd
  CI_IMAGE_NAME: noelmni/deep-fcd_ci

jobs:
  build_main_image:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || inputs.build_main == true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Build main Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.MAIN_IMAGE_NAME }}:latest

  build_ci_image:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch' || inputs.build_ci == true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Check for CI Dockerfile changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            ci:
              - 'ci/runner.Dockerfile'
              - 'ci/**'

      - name: Build CI runner Docker image
        if: steps.changes.outputs.ci == 'true' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: ./ci
          file: ./ci/runner.Dockerfile
          push: false
          tags: ${{ env.CI_IMAGE_NAME }}:cu122-ubuntu22.04-miniforge
          build-args: |
            BASE_IMAGE_TAG=12.2.2-cudnn8-devel-ubuntu22.04
            RUNNER_VERSION=2.328.0
