
name: Testing

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies for deepMask
        run: |
          wget https://raw.githubusercontent.com/NOEL-MNI/deepMask/main/app/requirements.txt -O /tmp/requirements.txt
          eval "$(conda shell.bash hook)"
          conda create -n preprocess python=3.8
          conda activate preprocess
          python -m pip install -r /tmp/requirements.txt
          conda deactivate

      - name: Install dependencies for deepFCD
        run: |
          python -m pip install -r ./app/requirements.txt
          conda install -c conda-forge pygpu==0.7.6
          pip cache purge

      - name: Download input files for inference # https://openneuro.org/datasets/ds004199/versions/1.0.5
        run: |
          wget https://s3.amazonaws.com/openneuro.org/ds004199/sub-00055/anat/sub-00055_acq-sag111_T1w.nii.gz\?versionId\=IKGWDiLR7B7ls2yPVyycJo.6R1Sqhujf -O ~/io/sub-00055/t1.nii.gz
          wget https://s3.amazonaws.com/openneuro.org/ds004199/sub-00055/anat/sub-00055_acq-tse3dvfl_FLAIR.nii.gz\?versionId\=HmzYoUuYkdbyd8jkpdJjVkZydRHNSqUX -O ~/io/sub-00055/flair.nii.gz
          wget https://s3.amazonaws.com/openneuro.org/ds004199/sub-00055/anat/sub-00055_acq-tse3dvfl_FLAIR_roi.nii.gz\?versionId\=ulmEU3nb8WCvGwcwTbkcdNSVr07PMPQN -O ~/io/sub-00055/label.nii.gz

      - name: Run inference for deepFCD
        run: |
          ./app/inference.py sub-00055 t1.nii.gz flair.nii.gz ~/io cuda 1 1